#!/bin/bash
echo "🔍 n8n Webhook Information Guide"
echo ""
echo "To find your webhook URL:"
echo ""
echo "1. Go to: https://trevathy.app.n8n.cloud"
echo "2. Open 'NIRA-the-BOT 2.0' workflow"
echo "3. Click on the Webhook node"
echo "4. Look for 'Webhook URL' or 'Path' in the settings panel"
echo "5. Copy the webhook ID (the part after /webhook/)"
echo ""
echo "Current webhook ID in your code:"
echo "  dbb33ceb-ed53-4dc1-8781-4d2786571d68"
echo ""
echo "If your actual webhook ID is different, update your .env file:"
echo "  VITE_N8N_WEBHOOK_URL=https://trevathy.app.n8n.cloud/webhook/YOUR-ACTUAL-ID"
echo ""
echo "Then restart your dev server and test again!"
